---
- name: Switch settings to default 
  hosts: localhost
  become: true

  vars:
    user_name: student2
    used_wallpaper: itmoscow.png
    config_path: "/home/{{user_name}}/.config/"
    wallpaper_local_path: /usr/share/wallpapers/
    wallpaper_url: "https://raw.githubusercontent.com/Restour1/ansible-IT-Moscow/main/playbooks/files/{{used_wallpaper}}"

  handlers:
    - name: "Перезапуск kde"
      command: "systemctl --user --machine={{user_name}}@.host restart plasma-plasmashell.service"

  collections:
    - name: community.general

  tasks:
    - name: Create file for example
      shell: "touch /tmp/hello"

    - name: Download wallpaper image
      get_url:
        url: "{{wallpaper_url}}"
        dest: "{{wallpaper_local_path}}{{used_wallpaper}}"
        mode: '0644'
        force: false

    - name: Set wallpaper
      community.general.kdeconfig:
        path: "{{ config_path }}plasma-org.kde.plasma.desktop-appletsrc"
        values:
          - groups: [Containments, 1, Wallpaper, org.kde.image, General]
            key: Image
            value: "{{ wallpaper_local_path }}{{ used_wallpaper }}"
        mode: '0644'
      notify: "Перезапуск kde"