---
- name: install server
  hosts: demo
  become: true
  vars:
    hostname: Example
    server_name: MyServer

  tasks:
    # - name "anywhere"
      # dnf:
      #   name: "name"

    # - name: "write name"
    #   shell: echo "host name $0"

      - name: Apache installer
        dnf:
          name: httpd
          state: present
          use_backend: dnf4

      - name: index.html from template
        template:
          src: index.html.j2
          dest: /var/www/html/index.html

      - name: Starter Apache
        service:
          name: httpd
          state: started