---
- name: Make dirs
  hosts: demo
  become: true

  vars:
    user_name: student2
    config_path: "/home/{{user_name}}/.config/"
    wallpaper_name: itmoscow.png
    wallpaper_path: /usr/share/wallpapers/

  handlers:
    - name: "Перезапуск kde"
      command: "systemctl --user --machine={{user_name}}@.host restart plasma-plasmashell.service"

  tasks:
    # - name: create dirs
    #   file:
    #     path: /usr/share/kde4/apps/desktoptheme/default/
    #     state: directory
    #     mode: '0755'

    - name: Copy wallpaper image
      copy:
        src: "files/{{ wallpaper_name }}"
        dest: "{{ wallpaper_path }}{{ wallpaper_name }}"
        owner: root
        group: root
        mode: '0644'

    - name: Set wallpaper
      community.general.kdeconfig:
        path: "{{ config_path }}plasma-org.kde.plasma.desktop-appletsrc"
        values:
          - groups: [Containments, 1, Wallpaper, org.kde.image, General]
            key: Image
            value: "{{ wallpaper_path }}{{ wallpaper_name }}"
        mode: '0644'
      notify: "Перезапуск kde"

    # - name: Set panel to bottom
    #   community.general.kdeconfig:
    #     path: "{{ config_path }}plasma-org.kde.plasma.desktop-appletsrc"
    #     values:
    #       - groups: [Containments, 1]
    #         key: location
    #         value: 4 #3 - top, 5 - left, 6 - right
    #   notify: "Перезапуск kde"
    
    # - name: Set light color theme
    #   community.general.kdeconfig:
    #     path: "{{ config_path }}kdeglobals"
    #     values:
    #       - group: [General]
    #         key: ColorScheme
    #         value: BreezeLight
    #   notify: "Перезапуск kde"